spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_02
    username: root
    password: 123456
  #解决swagger2报空指针问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9090



mybatis:
  mapper-locations: classpath:**/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


